In [2]:
# load data
import pandas as pd
df = pd.read_csv("ForeignGifts_edu.csv")
# avoiding scientific notation  
pd.set_option('display.float_format', lambda x: f'{x:.4f}')

In [3]:
# describe differences between different classes of gift types
df.groupby("Gift Type").describe()

                    ID                                                        \
                 count          mean          std     min       25%      50%
Gift Type
Contract       17274.0  14860.675408  8727.159706     2.0   7895.50  15892.5
Monetary Gift  10936.0  12920.029901  6970.950105     1.0   6925.75  12179.5
Real Estate       11.0  20888.818182  5664.792403  9246.0  23418.50  23421.0

                                    OPEID                 ...  \
                    75%      max    count           mean  ...
Gift Type                                                 ...
Contract       22316.75  28220.0  17274.0  264930.739840  ...
Monetary Gift  18119.25  28221.0  10936.0  223025.274323  ...
Real Estate    23447.50  23459.0     11.0  300081.818182  ...

              Foreign Gift Received Date          Foreign Gift Amount  \
                                     75%      max               count
Gift Type
Contract                         43503.0  44012.0             17274.0
Monetary Gift                    43403.0  43911.0             10936.0
Real Estate                      43510.5  43646.0                11.0

                                                                         \
                       mean           std       min       25%       50%
Gift Type
Contract       6.257945e+05  3.768217e+06 -537770.0   13757.5  110000.0
Monetary Gift  5.281504e+05  2.086487e+06       1.0     250.0   50000.0
Real Estate    1.335265e+06  1.412071e+06   39456.0  370574.5  667555.0


                     75%         max
Gift Type
Contract        366000.0  99999999.0
Monetary Gift   400000.0  48842186.0
Real Estate    2121736.0   4312000.0

[3 rows x 32 columns]

There are three classes of Gift Type: Contract, Monetary Gift, and Real Estate.

In [9]:
# which country gives the most money in total?
df.columns
df.groupby("Country of Giftor")["Foreign Gift Amount"].sum().sort_values(ascending=False).head()

Country of Giftor
QATAR           2706240869
ENGLAND         1464906771
CHINA           1237952112
SAUDI ARABIA    1065205930
BERMUDA          899593972
Name: Foreign Gift Amount, dtype: int64

Qatar gives the most money in total.

In [10]:
df.groupby("Country of Giftor").value_counts().head()

Country of Giftor  ID     OPEID   Institution Name                            City       State  Foreign Gift Received Date  Foreign Gift Amount  Gift Type      Giftor Name
AFGHANISTAN        12494  177500  University of Illinois at Urbana-Champaign  Champaign  IL     41799                       378900               Monetary Gift  Council for the Develop of Social      1
                   12495  177500  University of Illinois at Urbana-Champaign  Champaign  IL     41814                       1225689              Contract       Ministry of Health of Rwanda           1
                   22743  310000  Ohio University                             Athens     OH     43298                       121098               Contract       Mn Pub Wrks Islamic Rep Afghanistan    1
                   22745  310000  Ohio University                             Athens     OH     43361                       224000               Contract       Mn Pub Wrks Islamic Rep Afghanistan    1
                   22748  310000  Ohio University                             Athens     OH     43391                       171004               Contract       Mn Pub Wrks Islamic Rep Afghanistan    1
Name: count, dtype: int64

Afghanistan initiates the most gifts by count.

In [6]:
country_totals = df.groupby("Country of Giftor")["Foreign Gift Amount"].sum()
grand_total = df["Foreign Gift Amount"].sum()

country_pct = (country_totals / grand_total * 100).sort_values(ascending=False)
print(country_pct.head(10))

Country of Giftor
QATAR          16.3021
ENGLAND         8.8245
CHINA           7.4573
SAUDI ARABIA    6.4167
BERMUDA         5.4191
CANADA          5.4104
HONG KONG       5.3456
JAPAN           3.9514
SWITZERLAND     3.7342
INDIA           3.2502
Name: Foreign Gift Amount, dtype: float64

In [11]:
df.groupby("Country of Giftor")['Foreign Gift Amount'].mean().sort_values(ascending=False).head()

Country of Giftor
BERMUDA    7.688837e+06
ECUADOR    3.985140e+06
QATAR      3.905109e+06
ANTIGUA    3.435545e+06
JERSEY     3.064589e+06
Name: Foreign Gift Amount, dtype: float64

Bermuda gives the largest gifts on average.

In [12]:
df.columns

Index(['ID', 'OPEID', 'Institution Name', 'City', 'State',
       'Foreign Gift Received Date', 'Foreign Gift Amount', 'Gift Type',
       'Country of Giftor', 'Giftor Name'],
      dtype='str')

In [13]:
df.groupby("Institution Name")["Foreign Gift Amount"].sum().sort_values(ascending=False).head()

Institution Name
Carnegie Mellon University               1477922504
Cornell University                       1289937761
Harvard University                        954803610
Massachusetts Institute of Technology     859071692
Yale University                           613441311
Name: Foreign Gift Amount, dtype: int64

Carnegie Mellon University receives the most money in total.

In [15]:
df.groupby("Institution Name").value_counts().head()

Institution Name                     ID     OPEID    City         State  Foreign Gift Received Date  Foreign Gift Amount  Gift Type      Country of Giftor  Giftor Name
Adelphi University                   18289  266600   Garden City  NY     43098                       500000               Monetary Gift  FRANCE             Lionel Viret                           1
                                     18288  266600   Garden City  NY     43098                       250000               Monetary Gift  FRANCE             Lionel Viret                           1
                                     18287  266600   Garden City  NY     42919                       250000               Monetary Gift  FRANCE             Lionel Viret                           1
Albert Einstein College of Medicine  28221  4279700  Bronx        NY     43692                       1024469              Monetary Gift  ISRAEL             Estate of Alfred Gertrud Sommerguth    1
                                     28219  4279700  Bronx        NY     42907                       1064580              Contract       ENGLAND            Roche Products Limited                 1
Name: count, dtype: int64

Adelphi University receives the greatest number of gifts by count.

In [20]:
df.groupby("Institution Name")["Foreign Gift Amount"].agg(["mean", "median"])

                                                           mean       median
Institution Name
Adelphi University                                  333333.3333  250000.0000
Albert Einstein College of Medicine                 708730.8333  668340.5000
Alfred University                                  1355849.5000 1355849.5000
American University (The)                           872250.0000  994500.0000
Amherst College                                     389361.5000  389361.5000
...                                                         ...          ...
Wright State University                             846822.0000  846822.0000
Xavier University of Louisiana                       50442.3571   62847.0000
Yale University                                    1115347.8382  510967.0000
Yeshiva University                                  297397.0000  297397.0000
Young Americans College of the Performing Arts ...  560791.5000  560791.5000

[318 rows x 2 columns]

For institutions in which the mean gift is greater than the median, there is right-skew. Large donations are pulling up the average, but the median is unaffected by these outliers.

In [22]:
df.groupby(["Country of Giftor", "Institution Name"])["Foreign Gift Amount"].sum().sort_values(ascending=False).head()

Country of Giftor  Institution Name
QATAR              Cornell University            1018473315
BERMUDA            Carnegie Mellon University     750000000
QATAR              Texas A&M University           504099350
                   Carnegie Mellon University     425410702
                   Georgetown University          327128310
Name: Foreign Gift Amount, dtype: int64

The largest flow of a single country to a single instution is between Qatar and Cornell University.

There are only US academic institutions in the dataset. Is this question not functionally identical to question 1?